on:
  push:
    branches:
      - main
jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: 'MITY'
          server: '154.12.237.134'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: './var/www/portfolio.mity.dev/'
          remote_path: '/var/www/portfolio.mity.dev/'
          args: '-o ConnectTimeout=5'